name: myapp
description: A exported flutter project from FUNCTION12



# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  pubspec: ^2.3.0
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/image-2.png
    - assets/page-1/images/png-clipart-resistance-thermometer-computer-icons-temperature-fever-miscellaneous-measurement-thumbnail-1.png
    - assets/components/images/image-3.png
    - assets/components/images/n1-1.png
    - assets/page-1/images/depositphotos75400715-stock-photo-seedling-growing-in-hands-1.png
    - assets/page-1/images/.png
    - assets/page-1/images/png-transparent-relative-humidity-computer-icons-moisture-rain-humid-text-logo-monochrome-1.png
    - assets/components/images/png-clipart-resistance-thermometer-computer-icons-temperature-fever-miscellaneous-measurement-thumbnail-1-N28.png
    - assets/page-1/images/png-transparent-relative-humidity-computer-icons-moisture-rain-humid-text-logo-monochrome-2.png
    - assets/components/images/-JBv.png
    - assets/components/images/-1BS.png
    - assets/components/images/png-clipart-resistance-thermometer-computer-icons-temperature-fever-miscellaneous-measurement-thumbnail-2.png
    - assets/components/images/png-transparent-relative-humidity-computer-icons-moisture-rain-humid-text-logo-monochrome-1-mhv.png
    - assets/page-1/images/usercircle.png
    - assets/components/images/usercircle-Z7J.png
    - assets/page-1/images/-6d2.png
    - assets/components/images/png-transparent-relative-humidity-computer-icons-moisture-rain-humid-text-logo-monochrome-2-w2U.png
    - assets/page-1/images/image-3-E9r.png
    - assets/page-1/images/png-clipart-resistance-thermometer-computer-icons-temperature-fever-miscellaneous-measurement-thumbnail-2-4mi.png
    - assets/page-1/images/image-1.png
    - assets/components/images/depositphotos75400715-stock-photo-seedling-growing-in-hands-1-bg.png
    - assets/page-1/images/edit.png
    - assets/page-1/images/depositphotos75400715-stock-photo-seedling-growing-in-hands-1-bg-EAp.png
    - assets/components/images/image-2-5Ec.png
    - assets/components/images/image-1-ZXa.png
    - assets/page-1/images/n1-1-BSL.png
    - assets/page-1/images/depositphotos75400715-stock-photo-seedling-growing-in-hands-1-bg-u9N.png
    - assets/page-1/images/depositphotos75400715-stock-photo-seedling-growing-in-hands-1-bg-U4c.png
    - assets/page-1/images/n1-1-bFa.png
    - assets/components/images/expandleft.png
    - assets/page-1/images/depositphotos75400715-stock-photo-seedling-growing-in-hands-1-bg-bKS.png
    - assets/page-1/images/expandleft-G4C.png
    - assets/components/images/info.png
    - assets/components/images/edit-je4.png
    - assets/page-1/images/signinsqure.png
    - assets/page-1/images/depositphotos75400715-stock-photo-seedling-growing-in-hands-1-bg-Rt8.png
    - assets/page-1/images/depositphotos75400715-stock-photo-seedling-growing-in-hands-1-bg-ya4.png
    - assets/page-1/images/expandleft-e5r.png
    - assets/components/images/signinsqure-tEQ.png
    - assets/page-1/images/info-VU8.png
    - assets/page-1/images/expandleft-2on.png
    - assets/page-1/images/expandleft-eHA.png
    - assets/page-1/images/subtract.png
    - assets/page-1/images/image-4-bg.png
    - assets/page-1/images/image-5-bg.png
    - assets/page-1/images/expandleft-SF6.png
    - assets/components/images/depositphotos75400715-stock-photo-seedling-growing-in-hands-2.png
    - assets/page-1/images/rectangle-4166.png
    - assets/page-1/images/depositphotos75400715-stock-photo-seedling-growing-in-hands-2-Fzk.png
    - assets/page-1/images/imggg.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
